image: 'node:10.14'

variables:
  APP_PORT: '8080'
  HAS_GANACHE: 'false'
  HAS_DB: 'false'
  DB_SHOULD_DELETE: 'false'
  HAS_INGRESS: 'true'
  REPLICAS: '3'

stages:
  - setup
  - test
  - build
  - review
  - tag
  - deploy
  - e2e-test
  - release
  - publish
  - post-deploy
  - run-jobs

templates_version:
  stage: setup
  variables:
    GIT_STRATEGY: none
  script:
    - 'echo "Templates at last CI file update: https://git.brickblock.sh/devops/project-templates/tree/ac3744662776f9f726e2053b798dbfdce1b275fa"'
  except:
    refs:
      - tags
      - master
    variables:
      - '$CI_COMMIT_MESSAGE =~ /\[ci-release\]/'
  dependencies: []
  cache: {}

check_env_vars:
  stage: setup
  variables:
    GIT_STRATEGY: none
  script:
    - ': "${REVIEW_DOMAIN:?Environment variable REVIEW_DOMAIN needs to be set as a CI variable in the GitLab repo settings before running this script}"'
    - ': "${STAGING_DOMAIN:?Environment variable STAGING_DOMAIN needs to be set as a CI variable in the GitLab repo settings before running this script}"'
    - ': "${PRODUCTION_DOMAIN:?Environment variable PRODUCTION_DOMAIN needs to be set as a CI variable in the GitLab repo settings before running this script}"'
    - ': "${ZONE:?Environment variable ZONE needs to be set as a CI variable in the GitLab repo settings before running this script}"'
    - ': "${SENTRY_AUTH_TOKEN:?Environment variable SENTRY_AUTH_TOKEN needs to be set as a CI variable in the GitLab repo settings before running this script}"'
    - ': "${SLACK_WEBHOOK_URL:?Environment variable SLACK_WEBHOOK_URL needs to be set as a CI variable in the GitLab repo settings before running this script}"'
  dependencies: []
  cache: {}
  except:
    refs:
      - tags
      - master
    variables:
      - '$CI_COMMIT_MESSAGE =~ /\[ci-release\]/'

include:
  - 'https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/cache.yml'
  - 'https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/setup.yml'
  - 'https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/lint.yml'
  - 'https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/test.yml'
  - 'https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/flow.yml'
  - 'https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/flow-coverage.yml'
  - 'https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/build-image.yml'
  - 'https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/review.yml'
  - 'https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/staging.yml'
  - 'https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/production.yml'
  - 'https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/sentry-release-production.yml'
  - 'https://git.brickblock.sh/devops/project-templates/raw/master/gitlab-ci/purge.yml'
