// flow-typed signature: af6aa7f61cee5ce01dd42b4142d6e9e3
// flow-typed version: <<STUB>>/abi-decoder_v^1.2.0/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'abi-decoder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'abi-decoder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'abi-decoder/dist/abi-decoder' {
  declare module.exports: any;
}

declare module 'abi-decoder/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'abi-decoder/dist/abi-decoder.js' {
  declare module.exports: $Exports<'abi-decoder/dist/abi-decoder'>;
}
declare module 'abi-decoder/index' {
  declare module.exports: $Exports<'abi-decoder'>;
}
declare module 'abi-decoder/index.js' {
  declare module.exports: $Exports<'abi-decoder'>;
}
declare module 'abi-decoder/webpack.config.js' {
  declare module.exports: $Exports<'abi-decoder/webpack.config'>;
}
