// flow-typed signature: 387f1b7d7eaa90b13875f428364b8977
// flow-typed version: <<STUB>>/eslint-plugin-security_v>= 1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-security'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-security' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-security/rules/detect-buffer-noassert' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-child-process' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-disable-mustache-escape' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-eval-with-expression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-new-buffer' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-no-csrf-before-method-override' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-non-literal-fs-filename' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-non-literal-regexp' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-non-literal-require' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-object-injection' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-possible-timing-attacks' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-pseudoRandomBytes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-security/rules/detect-unsafe-regex' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-security/index' {
  declare module.exports: $Exports<'eslint-plugin-security'>;
}
declare module 'eslint-plugin-security/index.js' {
  declare module.exports: $Exports<'eslint-plugin-security'>;
}
declare module 'eslint-plugin-security/rules/detect-buffer-noassert.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-buffer-noassert'>;
}
declare module 'eslint-plugin-security/rules/detect-child-process.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-child-process'>;
}
declare module 'eslint-plugin-security/rules/detect-disable-mustache-escape.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-disable-mustache-escape'>;
}
declare module 'eslint-plugin-security/rules/detect-eval-with-expression.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-eval-with-expression'>;
}
declare module 'eslint-plugin-security/rules/detect-new-buffer.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-new-buffer'>;
}
declare module 'eslint-plugin-security/rules/detect-no-csrf-before-method-override.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-no-csrf-before-method-override'>;
}
declare module 'eslint-plugin-security/rules/detect-non-literal-fs-filename.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-non-literal-fs-filename'>;
}
declare module 'eslint-plugin-security/rules/detect-non-literal-regexp.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-non-literal-regexp'>;
}
declare module 'eslint-plugin-security/rules/detect-non-literal-require.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-non-literal-require'>;
}
declare module 'eslint-plugin-security/rules/detect-object-injection.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-object-injection'>;
}
declare module 'eslint-plugin-security/rules/detect-possible-timing-attacks.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-possible-timing-attacks'>;
}
declare module 'eslint-plugin-security/rules/detect-pseudoRandomBytes.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-pseudoRandomBytes'>;
}
declare module 'eslint-plugin-security/rules/detect-unsafe-regex.js' {
  declare module.exports: $Exports<'eslint-plugin-security/rules/detect-unsafe-regex'>;
}
