// flow-typed signature: 6bf0fa7fb08dc826c5e4fcd52b626ae1
// flow-typed version: <<STUB>>/eslint-plugin-react-redux_v>= 2/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-react-redux/lib/filterReports' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-redux/lib/isReactReduxConnect' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-redux/lib/rules/connect-prefer-minimum-two-arguments' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-redux/lib/rules/connect-prefer-named-arguments' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-redux/lib/rules/mapDispatchToProps-prefer-parameters-names' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-redux/lib/rules/mapDispatchToProps-prefer-shorthand' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-redux/lib/rules/mapDispatchToProps-returns-object' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-redux/lib/rules/mapStateToProps-no-store' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-redux/lib/rules/mapStateToProps-prefer-hoisted' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-redux/lib/rules/mapStateToProps-prefer-parameters-names' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-redux/lib/rules/no-unused-prop-types' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-redux/lib/rules/prefer-separate-component-file' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-redux/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-react-redux/index' {
  declare module.exports: $Exports<'eslint-plugin-react-redux'>;
}
declare module 'eslint-plugin-react-redux/index.js' {
  declare module.exports: $Exports<'eslint-plugin-react-redux'>;
}
declare module 'eslint-plugin-react-redux/lib/filterReports.js' {
  declare module.exports: $Exports<'eslint-plugin-react-redux/lib/filterReports'>;
}
declare module 'eslint-plugin-react-redux/lib/isReactReduxConnect.js' {
  declare module.exports: $Exports<'eslint-plugin-react-redux/lib/isReactReduxConnect'>;
}
declare module 'eslint-plugin-react-redux/lib/rules/connect-prefer-minimum-two-arguments.js' {
  declare module.exports: $Exports<'eslint-plugin-react-redux/lib/rules/connect-prefer-minimum-two-arguments'>;
}
declare module 'eslint-plugin-react-redux/lib/rules/connect-prefer-named-arguments.js' {
  declare module.exports: $Exports<'eslint-plugin-react-redux/lib/rules/connect-prefer-named-arguments'>;
}
declare module 'eslint-plugin-react-redux/lib/rules/mapDispatchToProps-prefer-parameters-names.js' {
  declare module.exports: $Exports<'eslint-plugin-react-redux/lib/rules/mapDispatchToProps-prefer-parameters-names'>;
}
declare module 'eslint-plugin-react-redux/lib/rules/mapDispatchToProps-prefer-shorthand.js' {
  declare module.exports: $Exports<'eslint-plugin-react-redux/lib/rules/mapDispatchToProps-prefer-shorthand'>;
}
declare module 'eslint-plugin-react-redux/lib/rules/mapDispatchToProps-returns-object.js' {
  declare module.exports: $Exports<'eslint-plugin-react-redux/lib/rules/mapDispatchToProps-returns-object'>;
}
declare module 'eslint-plugin-react-redux/lib/rules/mapStateToProps-no-store.js' {
  declare module.exports: $Exports<'eslint-plugin-react-redux/lib/rules/mapStateToProps-no-store'>;
}
declare module 'eslint-plugin-react-redux/lib/rules/mapStateToProps-prefer-hoisted.js' {
  declare module.exports: $Exports<'eslint-plugin-react-redux/lib/rules/mapStateToProps-prefer-hoisted'>;
}
declare module 'eslint-plugin-react-redux/lib/rules/mapStateToProps-prefer-parameters-names.js' {
  declare module.exports: $Exports<'eslint-plugin-react-redux/lib/rules/mapStateToProps-prefer-parameters-names'>;
}
declare module 'eslint-plugin-react-redux/lib/rules/no-unused-prop-types.js' {
  declare module.exports: $Exports<'eslint-plugin-react-redux/lib/rules/no-unused-prop-types'>;
}
declare module 'eslint-plugin-react-redux/lib/rules/prefer-separate-component-file.js' {
  declare module.exports: $Exports<'eslint-plugin-react-redux/lib/rules/prefer-separate-component-file'>;
}
declare module 'eslint-plugin-react-redux/lib/utils.js' {
  declare module.exports: $Exports<'eslint-plugin-react-redux/lib/utils'>;
}
