// flow-typed signature: 8098617cf6aec2b6d1f8670db64de160
// flow-typed version: <<STUB>>/eslint-plugin-react-ssr_v>= 1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react-ssr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react-ssr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-react-ssr/lib/rules/no-constructor-dom' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-ssr/lib/rules/no-will-mount-dom' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-ssr/lib/util/makeNoMethodDomRule' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-react-ssr/index' {
  declare module.exports: $Exports<'eslint-plugin-react-ssr'>;
}
declare module 'eslint-plugin-react-ssr/index.js' {
  declare module.exports: $Exports<'eslint-plugin-react-ssr'>;
}
declare module 'eslint-plugin-react-ssr/lib/rules/no-constructor-dom.js' {
  declare module.exports: $Exports<'eslint-plugin-react-ssr/lib/rules/no-constructor-dom'>;
}
declare module 'eslint-plugin-react-ssr/lib/rules/no-will-mount-dom.js' {
  declare module.exports: $Exports<'eslint-plugin-react-ssr/lib/rules/no-will-mount-dom'>;
}
declare module 'eslint-plugin-react-ssr/lib/util/makeNoMethodDomRule.js' {
  declare module.exports: $Exports<'eslint-plugin-react-ssr/lib/util/makeNoMethodDomRule'>;
}
