// flow-typed signature: 2d6999a0704603eae9de051372c256e3
// flow-typed version: <<STUB>>/flow-inlinestyle_v^1.0.9/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-inlinestyle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-inlinestyle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'flow-inlinestyle/index' {
  declare module.exports: $Exports<'flow-inlinestyle'>;
}
declare module 'flow-inlinestyle/index.js' {
  declare module.exports: $Exports<'flow-inlinestyle'>;
}
