// flow-typed signature: b27e0ef3ed9354a7467e99ae99021458
// flow-typed version: <<STUB>>/jsonlint-cli_v^1.0.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonlint-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonlint-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsonlint-cli/library/cli' {
  declare module.exports: any;
}

declare module 'jsonlint-cli/library/fetch-schema' {
  declare module.exports: any;
}

declare module 'jsonlint-cli/library/filter' {
  declare module.exports: any;
}

declare module 'jsonlint-cli/library/format' {
  declare module.exports: any;
}

declare module 'jsonlint-cli/library/get-configuration' {
  declare module.exports: any;
}

declare module 'jsonlint-cli/library/get-input' {
  declare module.exports: any;
}

declare module 'jsonlint-cli/library/help' {
  declare module.exports: any;
}

declare module 'jsonlint-cli/library/lint' {
  declare module.exports: any;
}

declare module 'jsonlint-cli/library/list-files' {
  declare module.exports: any;
}

declare module 'jsonlint-cli/library/load-schema' {
  declare module.exports: any;
}

declare module 'jsonlint-cli/library/print' {
  declare module.exports: any;
}

declare module 'jsonlint-cli/library/resolve-keys' {
  declare module.exports: any;
}

declare module 'jsonlint-cli/library/schema-error' {
  declare module.exports: any;
}

declare module 'jsonlint-cli/library/sort' {
  declare module.exports: any;
}

declare module 'jsonlint-cli/library/unknown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsonlint-cli/index' {
  declare module.exports: $Exports<'jsonlint-cli'>;
}
declare module 'jsonlint-cli/index.js' {
  declare module.exports: $Exports<'jsonlint-cli'>;
}
declare module 'jsonlint-cli/library/cli.js' {
  declare module.exports: $Exports<'jsonlint-cli/library/cli'>;
}
declare module 'jsonlint-cli/library/fetch-schema.js' {
  declare module.exports: $Exports<'jsonlint-cli/library/fetch-schema'>;
}
declare module 'jsonlint-cli/library/filter.js' {
  declare module.exports: $Exports<'jsonlint-cli/library/filter'>;
}
declare module 'jsonlint-cli/library/format.js' {
  declare module.exports: $Exports<'jsonlint-cli/library/format'>;
}
declare module 'jsonlint-cli/library/get-configuration.js' {
  declare module.exports: $Exports<'jsonlint-cli/library/get-configuration'>;
}
declare module 'jsonlint-cli/library/get-input.js' {
  declare module.exports: $Exports<'jsonlint-cli/library/get-input'>;
}
declare module 'jsonlint-cli/library/help.js' {
  declare module.exports: $Exports<'jsonlint-cli/library/help'>;
}
declare module 'jsonlint-cli/library/lint.js' {
  declare module.exports: $Exports<'jsonlint-cli/library/lint'>;
}
declare module 'jsonlint-cli/library/list-files.js' {
  declare module.exports: $Exports<'jsonlint-cli/library/list-files'>;
}
declare module 'jsonlint-cli/library/load-schema.js' {
  declare module.exports: $Exports<'jsonlint-cli/library/load-schema'>;
}
declare module 'jsonlint-cli/library/print.js' {
  declare module.exports: $Exports<'jsonlint-cli/library/print'>;
}
declare module 'jsonlint-cli/library/resolve-keys.js' {
  declare module.exports: $Exports<'jsonlint-cli/library/resolve-keys'>;
}
declare module 'jsonlint-cli/library/schema-error.js' {
  declare module.exports: $Exports<'jsonlint-cli/library/schema-error'>;
}
declare module 'jsonlint-cli/library/sort.js' {
  declare module.exports: $Exports<'jsonlint-cli/library/sort'>;
}
declare module 'jsonlint-cli/library/unknown.js' {
  declare module.exports: $Exports<'jsonlint-cli/library/unknown'>;
}
