// flow-typed signature: 75dc2fbab4df4fb67ec05cef6dae9cb4
// flow-typed version: <<STUB>>/notistack_v^0.6.1/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'notistack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'notistack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'notistack/build/index' {
  declare module.exports: any;
}

declare module 'notistack/build/RealProvider' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarContext' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarItem/index' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarItem/SnackbarItem' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarItem/SnackbarItem.styles' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarItem/SnackbarItem.util' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarProvider' {
  declare module.exports: any;
}

declare module 'notistack/build/SnackbarProvider.styles' {
  declare module.exports: any;
}

declare module 'notistack/build/useSnackbar' {
  declare module.exports: any;
}

declare module 'notistack/build/utils/capitalise' {
  declare module.exports: any;
}

declare module 'notistack/build/utils/constants' {
  declare module.exports: any;
}

declare module 'notistack/build/utils/warning' {
  declare module.exports: any;
}

declare module 'notistack/build/withSnackbar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'notistack/build/index.js' {
  declare module.exports: $Exports<'notistack/build/index'>;
}
declare module 'notistack/build/RealProvider.js' {
  declare module.exports: $Exports<'notistack/build/RealProvider'>;
}
declare module 'notistack/build/SnackbarContext.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarContext'>;
}
declare module 'notistack/build/SnackbarItem/index.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarItem/index'>;
}
declare module 'notistack/build/SnackbarItem/SnackbarItem.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarItem/SnackbarItem'>;
}
declare module 'notistack/build/SnackbarItem/SnackbarItem.styles.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarItem/SnackbarItem.styles'>;
}
declare module 'notistack/build/SnackbarItem/SnackbarItem.util.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarItem/SnackbarItem.util'>;
}
declare module 'notistack/build/SnackbarProvider.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarProvider'>;
}
declare module 'notistack/build/SnackbarProvider.styles.js' {
  declare module.exports: $Exports<'notistack/build/SnackbarProvider.styles'>;
}
declare module 'notistack/build/useSnackbar.js' {
  declare module.exports: $Exports<'notistack/build/useSnackbar'>;
}
declare module 'notistack/build/utils/capitalise.js' {
  declare module.exports: $Exports<'notistack/build/utils/capitalise'>;
}
declare module 'notistack/build/utils/constants.js' {
  declare module.exports: $Exports<'notistack/build/utils/constants'>;
}
declare module 'notistack/build/utils/warning.js' {
  declare module.exports: $Exports<'notistack/build/utils/warning'>;
}
declare module 'notistack/build/withSnackbar.js' {
  declare module.exports: $Exports<'notistack/build/withSnackbar'>;
}
