// flow-typed signature: b0240e110a9558c048c14f0ff025c7b9
// flow-typed version: <<STUB>>/number-to-words_v^1.2.4/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'number-to-words'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'number-to-words' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'number-to-words/numberToWords' {
  declare module.exports: any;
}

declare module 'number-to-words/numberToWords.min' {
  declare module.exports: any;
}

declare module 'number-to-words/spec/indexSpec' {
  declare module.exports: any;
}

declare module 'number-to-words/spec/isSafeNumberSpec' {
  declare module.exports: any;
}

declare module 'number-to-words/spec/phantom/run-jasmine3' {
  declare module.exports: any;
}

declare module 'number-to-words/spec/toOrdinalSpec' {
  declare module.exports: any;
}

declare module 'number-to-words/spec/toWordsOrdinalSpec' {
  declare module.exports: any;
}

declare module 'number-to-words/spec/toWordsSpec' {
  declare module.exports: any;
}

declare module 'number-to-words/src/index' {
  declare module.exports: any;
}

declare module 'number-to-words/src/isFinite' {
  declare module.exports: any;
}

declare module 'number-to-words/src/isSafeNumber' {
  declare module.exports: any;
}

declare module 'number-to-words/src/makeOrdinal' {
  declare module.exports: any;
}

declare module 'number-to-words/src/maxSafeInteger' {
  declare module.exports: any;
}

declare module 'number-to-words/src/toOrdinal' {
  declare module.exports: any;
}

declare module 'number-to-words/src/toWords' {
  declare module.exports: any;
}

declare module 'number-to-words/src/toWordsOrdinal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'number-to-words/numberToWords.js' {
  declare module.exports: $Exports<'number-to-words/numberToWords'>;
}
declare module 'number-to-words/numberToWords.min.js' {
  declare module.exports: $Exports<'number-to-words/numberToWords.min'>;
}
declare module 'number-to-words/spec/indexSpec.js' {
  declare module.exports: $Exports<'number-to-words/spec/indexSpec'>;
}
declare module 'number-to-words/spec/isSafeNumberSpec.js' {
  declare module.exports: $Exports<'number-to-words/spec/isSafeNumberSpec'>;
}
declare module 'number-to-words/spec/phantom/run-jasmine3.js' {
  declare module.exports: $Exports<'number-to-words/spec/phantom/run-jasmine3'>;
}
declare module 'number-to-words/spec/toOrdinalSpec.js' {
  declare module.exports: $Exports<'number-to-words/spec/toOrdinalSpec'>;
}
declare module 'number-to-words/spec/toWordsOrdinalSpec.js' {
  declare module.exports: $Exports<'number-to-words/spec/toWordsOrdinalSpec'>;
}
declare module 'number-to-words/spec/toWordsSpec.js' {
  declare module.exports: $Exports<'number-to-words/spec/toWordsSpec'>;
}
declare module 'number-to-words/src/index.js' {
  declare module.exports: $Exports<'number-to-words/src/index'>;
}
declare module 'number-to-words/src/isFinite.js' {
  declare module.exports: $Exports<'number-to-words/src/isFinite'>;
}
declare module 'number-to-words/src/isSafeNumber.js' {
  declare module.exports: $Exports<'number-to-words/src/isSafeNumber'>;
}
declare module 'number-to-words/src/makeOrdinal.js' {
  declare module.exports: $Exports<'number-to-words/src/makeOrdinal'>;
}
declare module 'number-to-words/src/maxSafeInteger.js' {
  declare module.exports: $Exports<'number-to-words/src/maxSafeInteger'>;
}
declare module 'number-to-words/src/toOrdinal.js' {
  declare module.exports: $Exports<'number-to-words/src/toOrdinal'>;
}
declare module 'number-to-words/src/toWords.js' {
  declare module.exports: $Exports<'number-to-words/src/toWords'>;
}
declare module 'number-to-words/src/toWordsOrdinal.js' {
  declare module.exports: $Exports<'number-to-words/src/toWordsOrdinal'>;
}
