// flow-typed signature: 55b986f32da7c0be3d608a438cc45de9
// flow-typed version: <<STUB>>/truffle-contract_v^4.0.11/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'truffle-contract'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'truffle-contract' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'truffle-contract/dist/truffle-contract' {
  declare module.exports: any;
}

declare module 'truffle-contract/dist/truffle-contract.min' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/contract' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/contract/bootstrap' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/contract/constructorMethods' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/contract/index' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/contract/properties' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/execute' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/handlers' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/override' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/reason' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/reformat' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/statuserror' {
  declare module.exports: any;
}

declare module 'truffle-contract/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'truffle-contract/dist/truffle-contract.js' {
  declare module.exports: $Exports<'truffle-contract/dist/truffle-contract'>;
}
declare module 'truffle-contract/dist/truffle-contract.min.js' {
  declare module.exports: $Exports<'truffle-contract/dist/truffle-contract.min'>;
}
declare module 'truffle-contract/index' {
  declare module.exports: $Exports<'truffle-contract'>;
}
declare module 'truffle-contract/index.js' {
  declare module.exports: $Exports<'truffle-contract'>;
}
declare module 'truffle-contract/lib/contract.js' {
  declare module.exports: $Exports<'truffle-contract/lib/contract'>;
}
declare module 'truffle-contract/lib/contract/bootstrap.js' {
  declare module.exports: $Exports<'truffle-contract/lib/contract/bootstrap'>;
}
declare module 'truffle-contract/lib/contract/constructorMethods.js' {
  declare module.exports: $Exports<'truffle-contract/lib/contract/constructorMethods'>;
}
declare module 'truffle-contract/lib/contract/index.js' {
  declare module.exports: $Exports<'truffle-contract/lib/contract/index'>;
}
declare module 'truffle-contract/lib/contract/properties.js' {
  declare module.exports: $Exports<'truffle-contract/lib/contract/properties'>;
}
declare module 'truffle-contract/lib/execute.js' {
  declare module.exports: $Exports<'truffle-contract/lib/execute'>;
}
declare module 'truffle-contract/lib/handlers.js' {
  declare module.exports: $Exports<'truffle-contract/lib/handlers'>;
}
declare module 'truffle-contract/lib/override.js' {
  declare module.exports: $Exports<'truffle-contract/lib/override'>;
}
declare module 'truffle-contract/lib/reason.js' {
  declare module.exports: $Exports<'truffle-contract/lib/reason'>;
}
declare module 'truffle-contract/lib/reformat.js' {
  declare module.exports: $Exports<'truffle-contract/lib/reformat'>;
}
declare module 'truffle-contract/lib/statuserror.js' {
  declare module.exports: $Exports<'truffle-contract/lib/statuserror'>;
}
declare module 'truffle-contract/lib/utils.js' {
  declare module.exports: $Exports<'truffle-contract/lib/utils'>;
}
