// flow-typed signature: 69fe6f3c2ef063c3994499f4296f0443
// flow-typed version: <<STUB>>/web3-utils_v^1.0.0-beta.52/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web3-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web3-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web3-utils/dist/web3-utils.cjs' {
  declare module.exports: any;
}

declare module 'web3-utils/dist/web3-utils.esm' {
  declare module.exports: any;
}

declare module 'web3-utils/dist/web3-utils.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web3-utils/dist/web3-utils.cjs.js' {
  declare module.exports: $Exports<'web3-utils/dist/web3-utils.cjs'>;
}
declare module 'web3-utils/dist/web3-utils.esm.js' {
  declare module.exports: $Exports<'web3-utils/dist/web3-utils.esm'>;
}
declare module 'web3-utils/dist/web3-utils.umd.js' {
  declare module.exports: $Exports<'web3-utils/dist/web3-utils.umd'>;
}
