// flow-typed signature: 9347c0c2168723fa6f8e8948b4d22651
// flow-typed version: <<STUB>>/yaml-lint_v^1.2.4/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yaml-lint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yaml-lint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yaml-lint/cli' {
  declare module.exports: any;
}

declare module 'yaml-lint/yaml-lint' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yaml-lint/cli.js' {
  declare module.exports: $Exports<'yaml-lint/cli'>;
}
declare module 'yaml-lint/yaml-lint.js' {
  declare module.exports: $Exports<'yaml-lint/yaml-lint'>;
}
