$id: http://git.brickblock.sh/platform/issuer-dashboard/blob/master/public/schema.yml
$schema: http://json-schema.org/draft-07/schema#
definitions: {}
type: object
title: Schema for the issuer-dashboard config
required:
  - sentry
  - etherscan
properties:
  sentry:
    $id: '#/properties/sentry'
    type: object
    title: The Sentry Schema
    required:
      - dsn
    properties:
      dsn:
        $id: '#/properties/sentry/properties/dsn'
        type: string
        format: uri
        title: The Sentry DSN (Data Source Name), needed to talk to the Sentry API
        default: https://<replace-me-with-a-real-dsn>@sentry.io
        examples:
          - https://12345678999999999999999999999999@sentry.io/1234567
  etherscan:
    $id: '#/properties/etherscan'
    type: object
    title: The Etherscan Schema
    required:
      - apiKey
    properties:
      dsn:
        $id: '#/properties/etherscan/properties/apiKey'
        type: string
        title: The Etherscan API key, needed to talk to the Etherscan API for fetching transaction data
        examples:
          - ABCDEF123456789AAAAAAAAAAAAAAAAAAA