// flow-typed signature: 2dc6e8909eb653f1e17583d8af5b78fc
// flow-typed version: <<STUB>>/@brickblock/eslint-config-base_v^4.1.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@brickblock/eslint-config-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@brickblock/eslint-config-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@brickblock/eslint-config-base/build/error-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/filename-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/flowtype-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/import-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/index' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/jest-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/prettier-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/promise-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/regex-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/security-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/unicorn-rules' {
  declare module.exports: any;
}

// Filename aliases
declare module '@brickblock/eslint-config-base/build/error-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/error-rules'>;
}
declare module '@brickblock/eslint-config-base/build/filename-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/filename-rules'>;
}
declare module '@brickblock/eslint-config-base/build/flowtype-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/flowtype-rules'>;
}
declare module '@brickblock/eslint-config-base/build/import-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/import-rules'>;
}
declare module '@brickblock/eslint-config-base/build/index.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/index'>;
}
declare module '@brickblock/eslint-config-base/build/jest-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/jest-rules'>;
}
declare module '@brickblock/eslint-config-base/build/prettier-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/prettier-rules'>;
}
declare module '@brickblock/eslint-config-base/build/promise-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/promise-rules'>;
}
declare module '@brickblock/eslint-config-base/build/regex-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/regex-rules'>;
}
declare module '@brickblock/eslint-config-base/build/security-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/security-rules'>;
}
declare module '@brickblock/eslint-config-base/build/unicorn-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/unicorn-rules'>;
}
