// flow-typed signature: 9e9a9512ec36239ba313620e54ec830a
// flow-typed version: <<STUB>>/@brickblock/eslint-config-react_v^2.3.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@brickblock/eslint-config-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@brickblock/eslint-config-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@brickblock/eslint-config-react/build/compat-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-react/build/css-modules-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-react/build/index' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-react/build/react-redux-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-react/build/react-rules' {
  declare module.exports: any;
}

// Filename aliases
declare module '@brickblock/eslint-config-react/build/compat-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-react/build/compat-rules'>;
}
declare module '@brickblock/eslint-config-react/build/css-modules-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-react/build/css-modules-rules'>;
}
declare module '@brickblock/eslint-config-react/build/index.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-react/build/index'>;
}
declare module '@brickblock/eslint-config-react/build/react-redux-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-react/build/react-redux-rules'>;
}
declare module '@brickblock/eslint-config-react/build/react-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-react/build/react-rules'>;
}
