// flow-typed signature: 9b2d89ae319482a4090a3f71b1921df3
// flow-typed version: <<STUB>>/@brickblock/eslint-config-base_v^4.2.2/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@brickblock/eslint-config-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@brickblock/eslint-config-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@brickblock/eslint-config-base/build/error-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/filename-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/flowtype-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/import-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/index' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/jest-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/prettier-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/promise-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/regex-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/security-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/build/unicorn-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/commitlint.config' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/@brickblock/eslint-config-base_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/@commitlint/cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/@commitlint/config-conventional_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/chalk_v2.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint-config-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-jest_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-promise_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-security_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-unicorn_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/flow-coverage-report_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/flow-remove-types_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/jest_v24.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/jsonlint_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/jsonlint-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/leasot_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/lint-staged_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/markdownlint-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/node-fetch_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/ora_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/prettier_v1.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/run.env_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/shelljs_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/standard-version_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/flow-typed/npm/yaml-lint_vx.x.x' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/prettier.config' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/scripts/healthcheck' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/error-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/filename-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/flowtype-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/import-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/index' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/jest-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/prettier-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/promise-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/regex-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/security-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/unicorn-rules' {
  declare module.exports: any;
}

// Filename aliases
declare module '@brickblock/eslint-config-base/build/error-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/error-rules'>;
}
declare module '@brickblock/eslint-config-base/build/filename-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/filename-rules'>;
}
declare module '@brickblock/eslint-config-base/build/flowtype-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/flowtype-rules'>;
}
declare module '@brickblock/eslint-config-base/build/import-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/import-rules'>;
}
declare module '@brickblock/eslint-config-base/build/index.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/index'>;
}
declare module '@brickblock/eslint-config-base/build/jest-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/jest-rules'>;
}
declare module '@brickblock/eslint-config-base/build/prettier-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/prettier-rules'>;
}
declare module '@brickblock/eslint-config-base/build/promise-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/promise-rules'>;
}
declare module '@brickblock/eslint-config-base/build/regex-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/regex-rules'>;
}
declare module '@brickblock/eslint-config-base/build/security-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/security-rules'>;
}
declare module '@brickblock/eslint-config-base/build/unicorn-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/build/unicorn-rules'>;
}
declare module '@brickblock/eslint-config-base/commitlint.config.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/commitlint.config'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/@brickblock/eslint-config-base_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/@brickblock/eslint-config-base_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/@commitlint/cli_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/@commitlint/cli_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/@commitlint/config-conventional_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/@commitlint/config-conventional_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/chalk_v2.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/chalk_v2.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint-config-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/eslint-config-prettier_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-jest_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-jest_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-prettier_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-promise_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-promise_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-security_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-security_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-unicorn_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/eslint-plugin-unicorn_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/flow-coverage-report_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/flow-coverage-report_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/flow-remove-types_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/flow-remove-types_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/husky_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/jest_v24.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/jest_v24.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/jsonlint_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/jsonlint_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/jsonlint-cli_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/jsonlint-cli_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/leasot_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/leasot_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/lint-staged_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/lint-staged_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/markdownlint-cli_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/markdownlint-cli_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/node-fetch_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/node-fetch_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/ora_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/ora_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/prettier_v1.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/prettier_v1.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/run.env_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/run.env_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/shelljs_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/shelljs_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/standard-version_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/standard-version_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/flow-typed/npm/yaml-lint_vx.x.x.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/flow-typed/npm/yaml-lint_vx.x.x'>;
}
declare module '@brickblock/eslint-config-base/prettier.config.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/prettier.config'>;
}
declare module '@brickblock/eslint-config-base/scripts/healthcheck.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/scripts/healthcheck'>;
}
declare module '@brickblock/eslint-config-base/src/error-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/error-rules'>;
}
declare module '@brickblock/eslint-config-base/src/filename-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/filename-rules'>;
}
declare module '@brickblock/eslint-config-base/src/flowtype-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/flowtype-rules'>;
}
declare module '@brickblock/eslint-config-base/src/import-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/import-rules'>;
}
declare module '@brickblock/eslint-config-base/src/index.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/index'>;
}
declare module '@brickblock/eslint-config-base/src/jest-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/jest-rules'>;
}
declare module '@brickblock/eslint-config-base/src/prettier-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/prettier-rules'>;
}
declare module '@brickblock/eslint-config-base/src/promise-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/promise-rules'>;
}
declare module '@brickblock/eslint-config-base/src/regex-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/regex-rules'>;
}
declare module '@brickblock/eslint-config-base/src/security-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/security-rules'>;
}
declare module '@brickblock/eslint-config-base/src/unicorn-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/unicorn-rules'>;
}
