// flow-typed signature: c14c21b544a4c68566dde258a16e3789
// flow-typed version: <<STUB>>/@brickblock/eslint-config-base_v^3.1.2/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@brickblock/eslint-config-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@brickblock/eslint-config-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@brickblock/eslint-config-base/src/error-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/filename-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/flowtype-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/import-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/jest-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/prettier-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/promise-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/regex-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/security-rules' {
  declare module.exports: any;
}

declare module '@brickblock/eslint-config-base/src/unicorn-rules' {
  declare module.exports: any;
}

// Filename aliases
declare module '@brickblock/eslint-config-base/index' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base'>;
}
declare module '@brickblock/eslint-config-base/index.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base'>;
}
declare module '@brickblock/eslint-config-base/src/error-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/error-rules'>;
}
declare module '@brickblock/eslint-config-base/src/filename-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/filename-rules'>;
}
declare module '@brickblock/eslint-config-base/src/flowtype-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/flowtype-rules'>;
}
declare module '@brickblock/eslint-config-base/src/import-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/import-rules'>;
}
declare module '@brickblock/eslint-config-base/src/jest-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/jest-rules'>;
}
declare module '@brickblock/eslint-config-base/src/prettier-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/prettier-rules'>;
}
declare module '@brickblock/eslint-config-base/src/promise-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/promise-rules'>;
}
declare module '@brickblock/eslint-config-base/src/regex-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/regex-rules'>;
}
declare module '@brickblock/eslint-config-base/src/security-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/security-rules'>;
}
declare module '@brickblock/eslint-config-base/src/unicorn-rules.js' {
  declare module.exports: $Exports<'@brickblock/eslint-config-base/src/unicorn-rules'>;
}
