// flow-typed signature: 4da8886e790a2769a3c64d42f0e86cad
// flow-typed version: <<STUB>>/@brickblock/smart-contracts_v^6.0.4/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@brickblock/smart-contracts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@brickblock/smart-contracts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@brickblock/smart-contracts/config/deployed-contracts' {
  declare module.exports: any;
}

declare module '@brickblock/smart-contracts/helpers/general' {
  declare module.exports: any;
}

declare module '@brickblock/smart-contracts/helpers/index' {
  declare module.exports: any;
}

declare module '@brickblock/smart-contracts/helpers/time-travel' {
  declare module.exports: any;
}

declare module '@brickblock/smart-contracts/migrations/helpers/arguments' {
  declare module.exports: any;
}

declare module '@brickblock/smart-contracts/migrations/helpers/bbk' {
  declare module.exports: any;
}

declare module '@brickblock/smart-contracts/migrations/helpers/constants' {
  declare module.exports: any;
}

declare module '@brickblock/smart-contracts/migrations/helpers/deployment' {
  declare module.exports: any;
}

declare module '@brickblock/smart-contracts/migrations/helpers/exchange-rates' {
  declare module.exports: any;
}

declare module '@brickblock/smart-contracts/migrations/helpers/general' {
  declare module.exports: any;
}

declare module '@brickblock/smart-contracts/migrations/helpers/index' {
  declare module.exports: any;
}

declare module '@brickblock/smart-contracts/migrations/helpers/owner-management' {
  declare module.exports: any;
}

declare module '@brickblock/smart-contracts/migrations/helpers/poa-manager' {
  declare module.exports: any;
}

declare module '@brickblock/smart-contracts/migrations/helpers/registry' {
  declare module.exports: any;
}

declare module '@brickblock/smart-contracts/migrations/helpers/statistics' {
  declare module.exports: any;
}

declare module '@brickblock/smart-contracts/migrations/helpers/whitelist' {
  declare module.exports: any;
}

declare module '@brickblock/smart-contracts/scripts/lib/logger' {
  declare module.exports: any;
}

declare module '@brickblock/smart-contracts/truffle' {
  declare module.exports: any;
}

// Filename aliases
declare module '@brickblock/smart-contracts/config/deployed-contracts.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/config/deployed-contracts'>;
}
declare module '@brickblock/smart-contracts/helpers/general.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/helpers/general'>;
}
declare module '@brickblock/smart-contracts/helpers/index.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/helpers/index'>;
}
declare module '@brickblock/smart-contracts/helpers/time-travel.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/helpers/time-travel'>;
}
declare module '@brickblock/smart-contracts/migrations/helpers/arguments.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/migrations/helpers/arguments'>;
}
declare module '@brickblock/smart-contracts/migrations/helpers/bbk.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/migrations/helpers/bbk'>;
}
declare module '@brickblock/smart-contracts/migrations/helpers/constants.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/migrations/helpers/constants'>;
}
declare module '@brickblock/smart-contracts/migrations/helpers/deployment.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/migrations/helpers/deployment'>;
}
declare module '@brickblock/smart-contracts/migrations/helpers/exchange-rates.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/migrations/helpers/exchange-rates'>;
}
declare module '@brickblock/smart-contracts/migrations/helpers/general.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/migrations/helpers/general'>;
}
declare module '@brickblock/smart-contracts/migrations/helpers/index.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/migrations/helpers/index'>;
}
declare module '@brickblock/smart-contracts/migrations/helpers/owner-management.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/migrations/helpers/owner-management'>;
}
declare module '@brickblock/smart-contracts/migrations/helpers/poa-manager.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/migrations/helpers/poa-manager'>;
}
declare module '@brickblock/smart-contracts/migrations/helpers/registry.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/migrations/helpers/registry'>;
}
declare module '@brickblock/smart-contracts/migrations/helpers/statistics.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/migrations/helpers/statistics'>;
}
declare module '@brickblock/smart-contracts/migrations/helpers/whitelist.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/migrations/helpers/whitelist'>;
}
declare module '@brickblock/smart-contracts/scripts/lib/logger.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/scripts/lib/logger'>;
}
declare module '@brickblock/smart-contracts/truffle.js' {
  declare module.exports: $Exports<'@brickblock/smart-contracts/truffle'>;
}
