// flow-typed signature: 6fcec74a6b082e321fe59cf5ec5dbf31
// flow-typed version: <<STUB>>/@ramda/compose_v^0.26.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ramda/compose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ramda/compose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ramda/compose/compose' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ramda/compose/compose.js' {
  declare module.exports: $Exports<'@ramda/compose/compose'>;
}
declare module '@ramda/compose/index' {
  declare module.exports: $Exports<'@ramda/compose'>;
}
declare module '@ramda/compose/index.js' {
  declare module.exports: $Exports<'@ramda/compose'>;
}
